ALTER TABLE AUTCALDA DROP CONSTRAINT PK_CALDA;
DROP TABLE AUTCALDA;
CREATE TABLE AUTCALDA
(
       CALDA_KEY  CHAR(06)  NOT NULL,                          -- ”NŒŽ
       CALDA_DD1  CHAR(02)  NOT NULL,                          -- “ú1
       CALDA_HLKB1  CHAR(01)  NOT NULL,                        -- ‹x“ú‹æ•ª1
       CALDA_WEEK1  CHAR(01)  NOT NULL,                        -- —j“ú‹æ•ª1
       CALDA_DD2  CHAR(02)  NOT NULL,                          -- “ú2
       CALDA_HLKB2  CHAR(01)  NOT NULL,                        -- ‹x“ú‹æ•ª2
       CALDA_WEEK2  CHAR(01)  NOT NULL,                        -- —j“ú‹æ•ª2
       CALDA_DD3  CHAR(02)  NOT NULL,                          -- “ú3
       CALDA_HLKB3  CHAR(01)  NOT NULL,                        -- ‹x“ú‹æ•ª3
       CALDA_WEEK3  CHAR(01)  NOT NULL,                        -- —j“ú‹æ•ª3
       CALDA_DD4  CHAR(02)  NOT NULL,                          -- “ú4
       CALDA_HLKB4  CHAR(01)  NOT NULL,                        -- ‹x“ú‹æ•ª4
       CALDA_WEEK4  CHAR(01)  NOT NULL,                        -- —j“ú‹æ•ª4
       CALDA_DD5  CHAR(02)  NOT NULL,                          -- “ú5
       CALDA_HLKB5  CHAR(01)  NOT NULL,                        -- ‹x“ú‹æ•ª5
       CALDA_WEEK5  CHAR(01)  NOT NULL,                        -- —j“ú‹æ•ª5
       CALDA_DD6  CHAR(02)  NOT NULL,                          -- “ú6
       CALDA_HLKB6  CHAR(01)  NOT NULL,                        -- ‹x“ú‹æ•ª6
       CALDA_WEEK6  CHAR(01)  NOT NULL,                        -- —j“ú‹æ•ª6
       CALDA_DD7  CHAR(02)  NOT NULL,                          -- “ú7
       CALDA_HLKB7  CHAR(01)  NOT NULL,                        -- ‹x“ú‹æ•ª7
       CALDA_WEEK7  CHAR(01)  NOT NULL,                        -- —j“ú‹æ•ª7
       CALDA_DD8  CHAR(02)  NOT NULL,                          -- “ú8
       CALDA_HLKB8  CHAR(01)  NOT NULL,                        -- ‹x“ú‹æ•ª8
       CALDA_WEEK8  CHAR(01)  NOT NULL,                        -- —j“ú‹æ•ª8
       CALDA_DD9  CHAR(02)  NOT NULL,                          -- “ú9
       CALDA_HLKB9  CHAR(01)  NOT NULL,                        -- ‹x“ú‹æ•ª9
       CALDA_WEEK9  CHAR(01)  NOT NULL,                        -- —j“ú‹æ•ª9
       CALDA_DD10  CHAR(02)  NOT NULL,                         -- “ú10
       CALDA_HLKB10  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª10
       CALDA_WEEK10  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª10
       CALDA_DD11  CHAR(02)  NOT NULL,                         -- “ú11
       CALDA_HLKB11  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª11
       CALDA_WEEK11  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª11
       CALDA_DD12  CHAR(02)  NOT NULL,                         -- “ú12
       CALDA_HLKB12  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª12
       CALDA_WEEK12  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª12
       CALDA_DD13  CHAR(02)  NOT NULL,                         -- “ú13
       CALDA_HLKB13  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª13
       CALDA_WEEK13  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª13
       CALDA_DD14  CHAR(02)  NOT NULL,                         -- “ú14
       CALDA_HLKB14  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª14
       CALDA_WEEK14  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª14
       CALDA_DD15  CHAR(02)  NOT NULL,                         -- “ú15
       CALDA_HLKB15  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª15
       CALDA_WEEK15  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª15
       CALDA_DD16  CHAR(02)  NOT NULL,                         -- “ú16
       CALDA_HLKB16  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª16
       CALDA_WEEK16  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª16
       CALDA_DD17  CHAR(02)  NOT NULL,                         -- “ú17
       CALDA_HLKB17  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª17
       CALDA_WEEK17  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª17
       CALDA_DD18  CHAR(02)  NOT NULL,                         -- “ú18
       CALDA_HLKB18  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª18
       CALDA_WEEK18  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª18
       CALDA_DD19  CHAR(02)  NOT NULL,                         -- “ú19
       CALDA_HLKB19  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª19
       CALDA_WEEK19  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª19
       CALDA_DD20  CHAR(02)  NOT NULL,                         -- “ú20
       CALDA_HLKB20  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª20
       CALDA_WEEK20  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª20
       CALDA_DD21  CHAR(02)  NOT NULL,                         -- “ú21
       CALDA_HLKB21  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª21
       CALDA_WEEK21  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª21
       CALDA_DD22  CHAR(02)  NOT NULL,                         -- “ú22
       CALDA_HLKB22  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª22
       CALDA_WEEK22  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª22
       CALDA_DD23  CHAR(02)  NOT NULL,                         -- “ú23
       CALDA_HLKB23  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª23
       CALDA_WEEK23  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª23
       CALDA_DD24  CHAR(02)  NOT NULL,                         -- “ú24
       CALDA_HLKB24  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª24
       CALDA_WEEK24  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª24
       CALDA_DD25  CHAR(02)  NOT NULL,                         -- “ú25
       CALDA_HLKB25  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª25
       CALDA_WEEK25  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª25
       CALDA_DD26  CHAR(02)  NOT NULL,                         -- “ú26
       CALDA_HLKB26  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª26
       CALDA_WEEK26  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª26
       CALDA_DD27  CHAR(02)  NOT NULL,                         -- “ú27
       CALDA_HLKB27  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª27
       CALDA_WEEK27  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª27
       CALDA_DD28  CHAR(02)  NOT NULL,                         -- “ú28
       CALDA_HLKB28  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª28
       CALDA_WEEK28  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª28
       CALDA_DD29  CHAR(02)  NOT NULL,                         -- “ú29
       CALDA_HLKB29  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª29
       CALDA_WEEK29  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª29
       CALDA_DD30  CHAR(02)  NOT NULL,                         -- “ú30
       CALDA_HLKB30  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª30
       CALDA_WEEK30  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª30
       CALDA_DD31  CHAR(02)  NOT NULL,                         -- “ú31
       CALDA_HLKB31  CHAR(01)  NOT NULL,                       -- ‹x“ú‹æ•ª31
       CALDA_WEEK31  CHAR(01)  NOT NULL,                       -- —j“ú‹æ•ª31
       CONSTRAINT PK_CALDA PRIMARY KEY(CALDA_KEY)
);
COMMIT;
