ALTER TABLE AUTCARNM DROP CONSTRAINT PK_CARNM;
DROP TABLE AUTCARNM;
CREATE TABLE AUTCARNM
(
       CARNM_SHSYCD  CHAR(01)  NOT NULL,                       -- é‘éÌCD
       CARNM_NAME  CHAR(20)  NOT NULL,                         -- ñºÅ@Å@èÃ
       CONSTRAINT PK_CARNM PRIMARY KEY(CARNM_SHSYCD)
);
COMMIT;
