ALTER TABLE AUTSYSFI DROP CONSTRAINT PK_SYSFI;
DROP TABLE AUTSYSFI;
CREATE TABLE AUTSYSFI
(
       SYSFI_KEY  CHAR(02)  NOT NULL,                          -- KEY="  "
       SYSFI_DATA  CHAR(53)  NOT NULL,                         -- DATA
       CONSTRAINT PK_SYSFI PRIMARY KEY(SYSFI_KEY)
);
COMMIT;
